import pandas as pd
from numpy.core.defchararray import upper

# Обновленный словарь марок и стран-производителей
brand_country = {
    'JEEP': 'USA',
    'ЛАДА': 'Russia',
    'ИЖ': 'Russia',
    'SKODA': 'Czech Republic',
    'LAND': 'UK',
    'SUZUKI': 'Japan',
    'OPEL': 'Germany',
    'SSANGYONG': 'South Korea',
    'MAZDA': 'Japan',
    'КАМАЗ': 'Russia',
    'LEXUS': 'Japan',
    'FIAT-HITACHI': 'Italy',
    'STALOWA': 'Poland',
    'HINO': 'Japan',
    'HAVAL': 'China',
    'MITSUBISHI': 'Japan',
    'SUBARU': 'Japan',
    'ИВАНОВЕЦ': 'Russia',
    'MAN': 'Germany',
    'SWIFT': 'India',
    'MERCEDES-BENZ': 'Germany',
    'PORSCHE': 'Germany',
    'DAEWOO': 'South Korea',
    'ГАЗ': 'Russia',
    'INFINITI': 'Japan',
    'SCANIA': 'Sweden',
    'ISUZU': 'Japan',
    'NICHIYU': 'Japan',
    'МАЗ': 'Belarus',
    'УАЗ': 'Russia',
    '172': 'Other',
    'МТЗ': 'Belarus',
    'ТОНАР': 'Russia',
    'GEELY': 'China',
    'ОТЗ': 'Russia',
    'НЕВА': 'Russia',
    'SDLG': 'China',
    'БЕЛАРУС': 'Belarus',
    'BOBCAT': 'USA',
    'KNAUS': 'Germany',
    'MINI': 'UK',
    'LIFAN': 'China',
    'SHIBAURA': 'Japan',
    'VORTEX': 'China',
    'DAIHATSU': 'Japan',
    'ЗИЛ': 'Russia',
    'BAOLI': 'China',
    'BYD': 'China',
    'FAW': 'China',
    'CADILLAC': 'USA',
    'IVECO': 'Italy',
    'РАСКАТ': 'Russia',
    'ЗАЗ': 'Ukraine',
    'CHERY': 'China',
    'КАВЗ': 'Russia',
    'HOWO': 'China',
    'ZOOMLION': 'China',
    'CAIMAN': 'France',
    'FOTON': 'China',
    'GMC': 'USA',
    'BRP': 'Canada',
    'DATSUN': 'Japan',
    'РОСТСЕЛЬМАШ': 'Russia',
    'BRILLIANCE': 'China',
    'ЛТЗ': 'Russia',
    'ПРОЧИЕ': 'Other',
    'KOMATSU': 'Japan',
    'ЮМЗ': 'Ukraine',
    'CHRYSLER': 'USA',
    'ГАЗСАЗ': 'Russia',
    'FUKAI': 'Japan',
    'ATLAS': 'Germany',
    'GREAT': 'China',
    'KUBOTA': 'Japan',
    'JAC': 'China',
    'IRAN': 'Iran',
    'SHAANXI': 'China',
    'CHANGAN': 'China',
    'RAVON': 'Uzbekistan',
    'KRONE': 'Germany',
    'DAF': 'Netherlands',
    'JAGUAR': 'UK',
    'ЮРМАШ': 'Russia',
    'ДРУГАЯ': 'Other',
    'МЗСА': 'Russia',
    'SCHMITZ': 'Germany',
    'DAYUN': 'China',
    'МОСКВИЧ': 'Russia',
    'BAILEY': 'UK',
    'JCB': 'UK',
    'WECAN': 'China',
    'ТРАКТОР': 'Other',
    'ALFA': 'Italy',
    'ROLFO': 'Italy',
    'HITACHI': 'Japan',
    'САМОДЕЛЬНАЯ': 'Other',
    'ХТЗ': 'Ukraine',
    'SITRAK': 'China',
    'LUGONG': 'China',
    'ZASLAW': 'Poland',
    'AICHI': 'Japan',
    'ТВЭКС': 'Russia',
    'FOXTANK': 'Other',
    'KASSBOHRER': 'Germany',
    'ACURA': 'Japan',
    'FREIGHTLINER': 'USA',
    'ARGO': 'Italy',
    'CONTAR': 'Other',
    'ISEKI': 'Japan',
    'KOBELCO': 'Japan',
    'HELI': 'China',
    'ТАГАЗ': 'Russia',
    'YANMAR': 'Japan',
    'AMMANN': 'Switzerland',
    'BURG': 'Netherlands',
    'ROVER': 'UK',
    'DONGFENG': 'China',
    'WORKER': 'Other',
    'HUMMER': 'USA',
    'ВГТЗ': 'Russia',
    'AIRMAN': 'Japan',
    'EXEED': 'China',
    'KATO': 'Japan',
    'DOOSAN': 'South Korea',
    'МЕДВЕДЬ': 'Russia',
    'SHACMAN': 'China',
    'УРАЛ': 'Russia',
    'НОВОСИБАРЗ': 'Russia',
    'CHEREAU': 'France',
    'БЗАП': 'Russia',
    'АМКОДОР': 'Belarus',
    'СЗАП': 'Russia',
    'HAMM': 'Germany',
    'CATERPILLAR': 'USA',
    'KOLUMAN': 'Turkey',
    'LONKING': 'China',
    'HINOMOTO': 'Japan',
    'СИБТРАЛ': 'Russia',
    'ЧЕТРА': 'Russia',
    'BOULDER': 'Other',
    'XCMG': 'China',
    'RBMOTORS': 'Russia',
    'ЛИАЗ': 'Russia',
    'КАЛАЧИНСКИЙ': 'Russia',
    'FENDT': 'Germany',
    'BULL': 'Other',
    'DENNISON': 'UK',
    'TRAILOR': 'France',
    'BAWOO': 'Other',
    'IWAFUJI': 'Japan',
    'KOGEL': 'Germany',
    'ABG': 'Germany',
    'CHIEFTAIN': 'UK',
    'YAMAHA': 'Japan',
    'UNIC': 'Japan',
    'BAW': 'China',
    'YIGONG': 'China',
    'БРОНТО': 'Russia',
    'ЧТЗ': 'Russia',
    'IHI': 'Japan',
    'НЕФАЗ': 'Russia',
    'XINGTAI': 'China',
    'ДЭК': 'Russia',
    'ВИС': 'Russia',
    'INTERNATIONAL': 'USA',
    'VERMEER': 'USA',
    'PONTIAC': 'USA',
    'ВЕЗДЕХОДНЫЕ': 'Other',
    'BONUM': 'Other',
    'КЕДР': 'Russia',
    'FERRARI': 'Italy',
    'LAMBORGHINI': 'Italy',
    'ЗАВОД': 'Other',
    'ROCLA': 'Finland',
    'LECITRAILER': 'Spain',
    'CAMC': 'China',
    'LAMBERET': 'France',
    'JMC': 'China',
    'ACKERMANN': 'Germany',
    'NOE': 'Other',
    'DODGE': 'USA',
    'ПАЗ': 'Russia',
    'ЭО': 'Other',
    'ELDDIS': 'UK',
    'XGMA': 'China',
    'BENTLEY': 'UK',
    'КИРОВЕЦ': 'Russia',
    'BORUS': 'Other',
    'SANY': 'China',
    'КЛИНЦЫ': 'Russia',
    'PROTON': 'Malaysia',
    'ZOTYE': 'China',
    'ГАЛИЧАНИН': 'Russia',
    'BMS': 'Other',
    'JUNJIN': 'South Korea',
    'DONGYANG': 'South Korea',
    'TOYOTA': 'Japan',
    'VOLKSWAGEN': 'Germany',
    'NISSAN': 'Japan',
    'BMW': 'Germany',
    'HYUNDAI': 'South Korea',
    'RENAULT': 'France',
    'FORD': 'USA',
    'KIA': 'South Korea',
    'HONDA': 'Japan',
    'AUDI': 'Germany',
    'CHEVROLET': 'USA',
    '172': 'Other',
    'PEUGEOT': 'France',
    'VOLVO': 'Sweden',
    'CITROEN': 'France',
    'FIAT': 'Italy',
    'ПРОЧИЕ': 'Other',
    'ДРУГАЯ': 'Other',
    'ТРАКТОР': 'Other',
    'САМОДЕЛЬНАЯ': 'Other',
    'FOXTANK': 'Other',
    'CONTAR': 'Other',
    'WORKER': 'Other',
    'BOULDER': 'Other',
    'BULL': 'Other',
    'BAWOO': 'Other',
    'ВЕЗДЕХОДНЫЕ': 'Other',
    'BONUM': 'Other',
    'SAAB': 'Sweden',
    'ЗАВОД': 'Other',
    'NOE': 'Other',
    'ЭО': 'Other',
    'BORUS': 'Other',
    'BMS': 'Other',
    'КЗАП': 'Other',
    'ДСТ-УРАЛ': 'Russia',
    'NAKATAKI': 'Other',
    'ЛУАЗ': 'Ukraine',
    'SHANTUI': 'China',
    'КАПРИ': 'Other',
    'NEW': 'Other',
    'SHIFENG': 'China',
    'TADANO': 'Japan',
    'MOLOT': 'Other',
    'КАРАКАТ': 'Other',
    'RAM': 'USA',
    'HZM': 'China',
    'YARS': 'Other',
    'SHEHWA': 'China',
    'TESLA': 'USA',
    'SUMITOMO': 'Japan',
    'SETRA': 'Germany',
    'ЧМЗАП': 'Russia',
    'ДНЕПР': 'Ukraine',
    'ТРАНСМАШ': 'Russia',
    'FAYMONVILLE': 'Belgium',
    'JOHN': 'USA',
    'SEAT': 'Spain',
    'TEREX': 'USA',
    'DACIA': 'Romania',
    'МАШЕКА': 'Belarus',
    'STELS': 'Russia',
    'ОРЕЛ-ПОГРУЗЧИК': 'Russia',
    'SCHWARZMULLER': 'Austria',
    'FLIEGL': 'Germany',
    'WIELTON': 'Poland',
    'MST': 'Turkey',
    'LOVOL': 'China',
    'СЕСПЕЛЬ': 'Russia',
    'LIUGONG': 'China',
    'САВ': 'Other',
    'AMUR': 'Russia',
    'KOREA': 'South Korea',
    'HIGER': 'China',
    'АЛЕКСЕЕВКА': 'Russia',
    'CASE': 'USA',
    'КОММАШ': 'Russia',
    'SUNWARD': 'China',
    'КОДАР': 'Other',
    'GENESIS': 'South Korea',
    'LAIGONG': 'China',
    'TATRA': 'Czech Republic',
    'ЧСДМ': 'Russia',
    'ДЗ': 'Russia',
    'КУРГАНСКИЕ': 'Russia',
    'КМЗ': 'Russia',
    'SMART': 'Germany',
    'FORCEMAX': 'Other',
    'ABBEY': 'UK',
    'LDV': 'UK',
    'МГБУ': 'Other',
    'ГУТ': 'Other',
    'FELIX': 'Other',
    'ОДАЗ': 'Russia',
    'NIIGATA': 'Japan',
    'MERLO': 'Italy',
    'АЛЯСКА': 'Other',
    'САРМАТ': 'Other',
    'МОСДИЗАЙНМАШ': 'Russia',
    'RUNMAX': 'Other',
    'NIPPON': 'Japan',
    'DINGLI': 'China',
    'PUTZMEISTER': 'Germany',
    'АТЗ': 'Other',
    'БЕЛАВА': 'Belarus',
    'ДОНИНВЕСТ': 'Other',
    'LIEBHERR': 'Germany',
    'ПАЛЕССЕ': 'Belarus',
    'ASTON': 'Other',
    'ЛЬВОВСКИЙ': 'Ukraine',
    'ПТЗ': 'Russia',
    'CIMC': 'China',
    'ТЮМЕНЬВЕЗДЕХОДСТРОЙ': 'Russia',
    'LAG': 'Belgium',
    'SVEDALA': 'Sweden',
    'BUICK': 'USA',
    'HANSELIFTER': 'Germany',
    'FARESIN': 'Italy',
    'ГРАЗ': 'Russia',
    'ASIA': 'South Korea',
    'ПМЗ': 'Russia',
    'ATMOS': 'Czech Republic',
    'SWATT': 'Other',
    'PONSSE': 'Finland',
    'GAC': 'China',
    'GEHL': 'USA',
    'ВЕЛМАШ': 'Russia',
    'SCHAEFF': 'Germany',
    'METACO': 'Other',
    'GENERAL': 'USA',
    'GRUNWALD': 'Russia',
    'HANIX': 'Japan',
    'IVECO-AMT': 'Russia',
    'PROKEEPER': 'Other',
    'HUATONG': 'China',
    'KENWORTH': 'USA',
    'БРЯНСКИЙ': 'Russia',
    'EP': 'Other',
    'ЛУИДОР-ТЮНИНГ': 'Russia',
    'ЛАЗ': 'Ukraine',
    'BLUMHARDT': 'Germany',
    'MINLE': 'China',
    'TIMBERJACK': 'USA',
    'XIN': 'China',
    'PALFINGER-SANY': 'Other',
    'ACMAR': 'Other',
    'SAMSUNG': 'South Korea',
    'PETERBILT': 'USA',
    'LINCOLN': 'USA',
    'FORWARD': 'Other',
    'PRINOTH': 'Italy',
    'ASA-LIFT': 'Denmark',
    'KOBASHI': 'Japan',
    'MERCURY': 'USA',
    'HBXG': 'China',
    'FRUEHAUF': 'USA',
    'ОХОТЕЦ': 'Other',
    'ROLLS-ROYCE': 'UK',
    'РМЗ': 'Russia',
    'ADRIA': 'Slovenia',
    'ZWALVE': 'Other',
    'MERCEDES': 'Germany',
    'YAROVIT': 'Russia',
    'JUTERBORG': 'Other',
    'УЛЬЯНОВЕЦ': 'Russia',
    'SEM': 'China',
    'HANTA': 'Japan',
    'УРАЛВАГОНЗАВОД': 'Russia',
    'ЧЕЛЯБИНЕЦ': 'Russia',
    'СТРОЙМАТИК': 'Russia',
    'ZX': 'Other',
    'HAFEI': 'China',
    'KAWABE': 'Japan',
    'CHALLENGER': 'USA',
    'ЦПП': 'Other',
    'MANITOU': 'France',
    'VENIERI': 'Italy',
    'ВИПО': 'Other',
    'KIP': 'Other',
    'УРАЛСПЕЦТРАНС': 'Russia',
    'TES': 'Other',
    'КРАНЭКС': 'Russia',
    'SHANLIN': 'China',
    'ШТОРМ': 'Russia',
    'ЗИФ': 'Russia',
    'ТРЭКОЛ': 'Russia',
    'AGRIMEC': 'Other',
    'NISSHA': 'Japan',
    'GT7': 'Other',
    'FORWAY': 'China',
    'ATLANT': 'Other',
    'MASSEY': 'Other',
    'TCM': 'Japan',
    'JINWOO': 'Other',
    'KOHO': 'Other',
    'ESTERER': 'Germany',
    'LGMG': 'China',
    'BIZON': 'Poland',
    'DIECI': 'Italy',
    'КРАЯН': 'Other',
    'ПОЛИТРАНС': 'Other',
    'FURUKAWA': 'Japan',
    'GURLESENYIL': 'Turkey',
    'SHANDONG': 'China',
    'RM-TEREX': 'Russia',
    'DYNAPAC': 'Sweden',
    'BALKANCAR': 'Bulgaria',
    'ММЗ': 'Belarus',
    'MULTICAR': 'Germany',
    'ВТЗ': 'Russia',
    'ABI': 'Other',
    'HANSIN': 'South Korea',
    'CAMRO': 'Other',
    'KATAYAMA': 'Other',
    'HANGCHA': 'China',
    'ТАПЗ': 'Russia',
    'ИРКУТСКИЙ': 'Russia',
    'HAIMA': 'China',
    'BEYERLAND': 'Netherlands',
    'БОГДАН': 'Ukraine',
    'GRIZZLY': 'Other',
    'ZETTELMEYER': 'Germany',
    'САМУРАЙ': 'Other',
    'ZEEKR': 'China',
    'VAZ': 'Russia',
    'ACE': 'United Kingdom',
    'ACERBI': 'Italy',
    'ACKERMANN': 'Germany',
    'ACURA': 'Japan',
    'ADR': 'Italy',
    'AFA': 'Turkey',
    'AGG': 'Germany',
    'AICHI': 'Japan',
    'AIMIX': 'China',
    'AIRMAN': 'Japan',
    'ALFA': 'Italy',
    'ALI': 'Italy',
    'ALKA': 'Turkey',
    'ALLOY': 'United Kingdom',
    'AMMANN': 'Switzerland',
    'AMUR': 'Russia',
    'ANT': 'Russia',
    'ARGO': 'Italy',
    'ASIA': 'South Korea',
    'ASTON_MARTIN': 'United Kingdom',
    'ASTRA': 'Italy',
    'ATLAS': 'Germany',
    'ATOMTECHNICS': 'Russia',
    'AUDI': 'Germany',
    'AVONDALE': 'United Kingdom',
    'BAIC': 'China',
    'BAILEY': 'United Kingdom',
    'BALKANCAR': 'Bulgaria',
    'BAUER': 'Germany',
    'BAW': 'China',
    'BEEZONE': 'Italy',
    'BENTLEY': 'United Kingdom',
    'BERGER': 'Germany',
    'BERGHEL': 'Italy',
    'BIZON': 'Poland',
    'BMW': 'Germany',
    'BODEX': 'Poland',
    'BOECKMANN': 'Germany',
    'BOMAG': 'Germany',
    'BOURGAULT': 'Canada',
    'BRILLIANCE': 'China',
    'BRP': 'Canada',
    'BUICK': 'USA',
    'BURG': 'Netherlands',
    'BYD': 'China',
    'CADILLAC': 'USA',
    'CAIMAN': 'Russia',
    'CAMC': 'China',
    'CARMIX': 'Italy',
    'CARNEHL': 'Germany',
    'CARTER': 'USA',
    'CASE': 'USA',
    'CASELLI': 'Italy',
    'CFMOTO': 'China',
    'CHANGAN': 'China',
    'CHANGCHUN': 'China',
    'CHANGLIN': 'China',
    'CHATEAU': 'France',
    'CHEREAU': 'France',
    'CHERY': 'China',
    'CHERYEXEED': 'China',
    'CHEVROLET': 'USA',
    'CHIKUSUI': 'Japan',
    'CHRYSLER': 'USA',
    'CIMC': 'China',
    'CITROEN': 'France',
    'CLAAS': 'Germany',
    'CLPC': 'China',
    'COACHMAN': 'United Kingdom',
    'COMPASS': 'United Kingdom',
    'CTTM': 'China',
    'CUKUROVA': 'Turkey',
    'DACIA': 'Romania',
    'DAEWOO': 'South Korea',
    'DAHAN': 'China',
    'DAIHATSU': 'Japan',
    'DALIAN': 'China',
    'DASAN': 'South Korea',
    'DATSUN': 'Japan',
    'DAYUN': 'China',
    'DEMAG': 'Germany',
    'DENNISON': 'United Kingdom',
    'DENYO': 'Japan',
    'DERWAYS': 'Russia',
    'DETVAN': 'Russia',
    'DIECI': 'Italy',
    'DINGLI': 'China',
    'DITCH': 'USA',
    'DM': 'Italy',
    'DODGE': 'USA',
    'DONGFENG': 'China',
    'DRESSTA': 'Poland',
    'DW': 'China',
    'DW-TXS': 'China',
    'DYNAPAC': 'Sweden',
    'ELDDIS': 'United Kingdom',
    'EVERDIGM': 'South Korea',
    'EVOLUTE': 'Russia',
    'EXEED': 'China',
    'FARESIN': 'Italy',
    'FAW': 'China',
    'FAYMONVILLE': 'Belgium',
    'FELDBINDER': 'Germany',
    'FENDT': 'Germany',
    'FERRARI': 'Italy',
    'FIAT': 'Italy',
    'FIAT-HITACHI': 'Italy',
    'FIORI': 'Italy',
    'FLIEGL': 'Germany',
    'FORD': 'USA',
    'FORT': 'China',
    'FORWAY': 'China',
    'FORZA': 'China',
    'FRONTAL': 'Russia',
    'FRONTMEN': 'Italy',
    'FRUEHAUF': 'France',
    'FUCHS': 'Germany',
    'FUJII': 'Japan',
    'FUKAI': 'China',
    'FURUKAWA': 'Japan',
    'GAC': 'China',
    'GEELY': 'China',
    'GEHL': 'USA',
    'GENERAL': 'USA',
    'GENESIS': 'South Korea',
    'GMC': 'USA',
    'GOODSENSE': 'China',
    'GRAY': 'USA',
    'GREAT': 'China',
    'GROENEWEGEN': 'Netherlands',
    'GRUNWALD': 'Germany',
    'GUTEWOLF': 'Germany',
    'HAFEI': 'China',
    'HAIMA': 'China',
    'HAITUI': 'China',
    'HAMM': 'Germany',
    'HANGCHA': 'China',
    'HANIA': 'China',
    'HANIX': 'Japan',
    'HANSIN': 'South Korea',
    'HANTA': 'Japan',
    'HARTUNG': 'Russia',
    'HAULOTTE': 'France',
    'HAVAL': 'China',
    'HAWTAI': 'China',
    'HBM-NOBAS': 'Germany',
    'HEIL': 'USA',
    'HELFFER': 'Italy',
    'HELI': 'China',
    'HENDRICKS': 'USA',
    'HIDROMEK': 'Turkey',
    'HINOMOTO': 'Japan',
    'HONDA': 'Japan',
    'HONGQI': 'China',
    'HORYONG': 'South Korea',
    'HUMMER': 'USA',
    'HYSTER': 'USA',
    'HYUNDAI': 'South Korea',
    'HZM': 'China',
    'IFA': 'Germany',
    'IHI': 'Japan',
    'IKARUS': 'Hungary',
    'INFINITI': 'Japan',
    'IRAN': 'Iran',
    'ISEKI': 'Japan',
    'ISUZU': 'Japan',
    'IWAFUJI': 'Japan',
    'JAC': 'China',
    'JAGUAR': 'United Kingdom',
    'JCB': 'United Kingdom',
    'JEEP': 'USA',
    'JETTA': 'Germany',
    'JIEFANG': 'China',
    'JLG': 'USA',
    'JMC': 'China',
    'JOHN': 'USA',
    'JUNGHEINRICH': 'Germany',
    'JUNJIN': 'South Korea',
    'KAISHAN': 'China',
    'KASSBOHRER': 'Germany',
    'KATO': 'Japan',
    'KAWABE': 'Japan',
    'KAWASAKI': 'Japan',
    'KCP': 'South Korea',
    'KELBERG': 'Denmark',
    'KIA': 'South Korea',
    'KING': 'China',
    'KOBASHI': 'Japan',
    'KOBELCO': 'Japan',
    'KOGEL': 'Germany',
    'KOLUMAN': 'Turkey',
    'KOREA': 'South Korea',
    'KRONE': 'Germany',
    'KUBOTA': 'Japan',
    'LAG': 'Belgium',
    'LAIGONG': 'China',
    'LAMBERET': 'France',
    'LAMBORGHINI': 'Italy',
    'LANCIA': 'Italy',
    'LAND': 'United Kingdom',
    'LAND_ROVER': 'United Kingdom',
    'LANGENDORF': 'Germany',
    'LDV': 'United Kingdom',
    'LECITRAILER': 'Spain',
    'LEIST': 'Germany',
    'LEXUS': 'Japan',
    'LI': 'China',
    'LIEBHERR': 'Germany',
    'LIFAN': 'China',
    'LINCOLN': 'USA',
    'LINDE': 'Germany',
    'LIUGONG': 'China',
    'LOCUST': 'Slovakia',
    'LOHR': 'France',
    'LONGGONG': 'China',
    'LONKING': 'China',
    'LUGONG': 'China',
    'LUNAR': 'United Kingdom',
    'LUTONG': 'China',
    'LUXGEN': 'Taiwan',
    'MANITOU': 'France',
    'MASERATI': 'Italy',
    'MAXIMAL': 'China',
    'MAXSTREL': 'Russia',
    'MAZDA': 'Japan',
    'MECALAC': 'France',
    'MEGA': 'Poland',
    'MERCEDES': 'Germany',
    'MERCEDES-BENZ': 'Germany',
    'MERCURY': 'USA',
    'MESDA': 'China',
    'METSO': 'Finland',
    'MEUSBURGER': 'Austria',
    'MG': 'United Kingdom',
    'MIKASA': 'Japan',
    'MINI': 'United Kingdom',
    'MITSUBER': 'China',
    'MITSUBISHI': 'Japan',
    'MITSUI': 'Japan',
    'MONTRACON': 'United Kingdom',
    'MOROOKA': 'Japan',
    'MST': 'Turkey',
    'MULTIONE': 'Italy',
    'MUSTANG': 'USA',
    'NARKO': 'Russia',
    'NAVECO': 'China',
    'NEMAN': 'Belarus',
    'NEO': 'China',
    'NICHIJO': 'Japan',
    'NICHIYU': 'Japan',
    'NIIGATA': 'Japan',
    'NIO': 'China',
    'NIPPON': 'Japan',
    'NISSAN': 'Japan',
    'NURSAN': 'Turkey',
    'OHARA': 'Japan',
    'OMODA': 'China',
    'OPEL': 'Germany',
    'ORTHAUS': 'Germany',
    'OZGUL': 'Turkey',
    'PEUGEOT': 'France',
    'PLYMOUTH': 'USA',
    'POLARIS': 'USA',
    'PONSSE': 'Finland',
    'PONTIAC': 'USA',
    'PORSCHE': 'Germany',
    'POWERSCREEN': 'United Kingdom',
    'PROTON': 'Malaysia',
    'RAM': 'USA',
    'RANGER': 'USA',
    'RAVON': 'Uzbekistan',
    'RBMOTORS': 'Russia',
    'REAL': 'Russia',
    'RED': 'China',
    'REDSTAR': 'China',
    'RENAULT': 'France',
    'RENDERS': 'Belgium',
    'RM-TEREX': 'Russia',
    'ROLFO': 'Italy',
    'ROLLS-ROYCE': 'United Kingdom',
    'RONGWEI': 'China',
    'ROVER': 'United Kingdom',
    'SAAB': 'Sweden',
    'SAKAI': 'Japan',
    'SAMRO': 'France',
    'SAMSUNG': 'South Korea',
    'SATURN': 'USA',
    'SCANIA': 'Sweden',
    'SCHMITZ': 'Germany',
    'SCHWARZMULLER': 'Austria',
    'SCHWERINER': 'Germany',
    'SCION': 'Japan',
    'SDLG': 'China',
    'SEAT': 'Spain',
    'SEM': 'China',
    'SENNEBOGEN': 'Germany',
    'SEVER': 'Russia',
    'SHANDONG': 'China',
    'SHANLIN': 'China',
    'SHANMON': 'China',
    'SHEHWA': 'China',
    'SHIBAURA': 'Japan',
    'SHIFENG': 'China',
    'SHINDAIWA': 'Japan',
    'SHTORM': 'Russia',
    'SIKOKU': 'Japan',
    'SINOMACH': 'China',
    'SKODA': 'Czech Republic',
    'SKYWELL': 'China',
    'SMART': 'Germany',
    'SOMMER': 'Germany',
    'SOR': 'Spain',
    'SPRITE': 'United Kingdom',
    'SSANGYONG': 'South Korea',
    'STALOWA': 'Poland',
    'STEELBEAR': 'Russia',
    'STELS': 'Russia',
    'STERLING': 'USA',
    'STILL': 'Germany',
    'STRONG': 'Russia',
    'SUBARU': 'Japan',
    'SUMITOMO': 'Japan',
    'SUZUKI': 'Japan',
    'SWIFT': 'United Kingdom',
    'SZM': 'Russia',
    'TABBERT': 'Germany',
    'TAKEUCHI': 'Japan',
    'TANK': 'China',
    'TATA': 'India',
    'TCM': 'Japan',
    'TEC': 'Germany',
    'TEREX': 'USA',
    'TESLA': 'USA',
    'TFN': 'China',
    'TIANMA': 'China',
    'TIANYE': 'China',
    'TIGERCAT': 'Canada',
    'TIMBERJACK': 'USA',
    'TINGER': 'Russia',
    'TITAN': 'USA',
    'TOKYU': 'Japan',
    'TONGYADA': 'China',
    'TOYOTA': 'Japan',
    'TRAILMOBIL': 'USA',
    'TRAILOR': 'France',
    'TRF': 'China',
    'TROUILLET': 'France',
    'TSS': 'Russia',
    'TUNDRA': 'USA',
    'UD': 'Japan',
    'ULAN-RT': 'Russia',
    'UMG': 'Russia',
    'UNC': 'Czech Republic',
    'UNIC': 'Japan',
    'UNICARRIERS': 'Japan',
    'UTILITY': 'USA',
    'VALMET': 'Finland',
    'VAN': 'Netherlands',
    'VAZ': 'Russia',
    'VERMEER': 'USA',
    'VIKING': 'USA',
    'VOGELE': 'Germany',
    'VOLKSWAGEN': 'Germany',
    'VOLVO': 'Sweden',
    'VORTEX': 'China',
    'VOYAH': 'China',
    'WABASH': 'USA',
    'WACKER': 'Germany',
    'WADO': 'Japan',
    'WANSHIDA': 'China',
    'WECAN': 'China',
    'WEITUO': 'China',
    'WELTMEISTER': 'China',
    'WIELTON': 'Poland',
    'WIRTGEN': 'Germany',
    'XCMG': 'China',
    'XGMA': 'China',
    'XILIN': 'China',
    'XINGTAI': 'China',
    'XINYUAN': 'China',
    'XPENG': 'China',
    'YAFENG': 'China',
    'YALE': 'USA',
    'YAMAHA': 'Japan',
    'YANASE': 'Japan',
    'YANMAR': 'Japan',
    'YIGONG': 'China',
    'YUCHAI': 'China',
    'YUEJIN': 'China',
    'YUGONG': 'China',
    'ZAUBERG': 'Germany',
    'ZEEKR': 'China',
    'ZEMAG': 'Germany',
    'ZOOMLION': 'China',
    'ZOTYE': 'China',
    'БЕЛАРУС': 'Belarus',
    'ЛАДА': 'Russia',
    'МОСКВИЧ': 'Russia',
    'УАЗ': 'Russia',
    'ФАЙТЕР': 'Russia',
    'ФЕНИКС': 'Russia',
    "JETOUR": "China"
}

# Путь к файлу с исходным датасетом в формате CSV
csv_file_path = 'data/merged_result.csv'

# Загрузка датасета
df = pd.read_csv(csv_file_path, low_memory=False)
df['power'] = df['power'].fillna(0)
df['probeg'] = df['probeg'].fillna(0)
df['R'] = df['R'].fillna(0)
df['G'] = df['G'].fillna(0)
df['B'] = df['B'].fillna(0)


df["cost"] = df["cost"].astype("int")
df["currency"] = df["currency"].astype("string")
df["marka"] = df["marka"].astype("string")
df["model"] = df["model"].astype("string")
df["year"] = df["year"].astype('string')[:-2]
df["has_license"] = pd.to_numeric(df["has_license"], errors='coerce').astype('Int64')
df["place"] = df["place"].astype("string")
df["date"] = df["date"].astype("string")
df["probeg"] = df["probeg"].astype("int")
df["id"] = pd.to_numeric(df["id"], errors='coerce').astype('Int64')
df["engine"] = df["engine"].astype("string")
df["power"] = pd.to_numeric(df["power"], errors='coerce').astype('Int64')
df["gear"] = df["gear"].astype("string")
df["sWheel"] = df["sWheel"].astype("string")
df["complectation"] = df["complectation"].astype("string")
df["transmission"] = df["transmission"].astype("string")
df["R"] = pd.to_numeric(df["R"], errors='coerce').astype('Int64')
df["G"] = pd.to_numeric(df["G"], errors='coerce').astype('Int64')
df["B"] = pd.to_numeric(df["B"], errors='coerce').astype('Int64')
df['country'] = df['marka'].str.upper().map(brand_country).fillna('Other')

# Сохранение обновленного датасета
df.to_csv('updated_dataset.csv', index=False)

print("Датасет успешно обновлен и сохранен как 'updated_dataset.csv'")
